module.exports = {
  SMART_CONTRACT: {
    HASH: '0x10cbB0F4B3348df82ed6AAeC9C17E8045222fA62',
    PATH: 'ABI-DO-SMART-CONTRACT-ESTA-DENTRO-DA-PASTA-BUILD',
    CALLER: 'ENDERECO-DA-SUA-CARTEIRA',
    GAS_LIMIT: 6721975
  },
  WEB3: {
    PROVIDER: 'https://ropsten.infura.io/v3/XXXXXXXXXXXXXXXXXX',
    PRIVATE_KEY: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
  }
};
